openapi: '3.0.3'
info:
  title: API Title
  version: '1.0'
servers:
  - url: http://localhost:3000
paths:
  /test:
    post:
      parameters:
        - in: query
          name: color
          schema:
            type: array
            items:
              type: string
          # Serialize as color=blue,black,brown (default)
          style: form
          explode: false
      responses:
        200:
          description: OK
