openapi: '3.0.3'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /info/logo:
    get:
      responses:
        '200': # Resp
          description: OK
          content: # Resp body
            image/*: # Media type
              schema:
                type: string
                format: binary
